### ISSUE TITLE
Fogcell and Fogcontrolnode not compiling

### ISSUE THREAD

**Issue by vipin-singh1** [softls/FogFrame-2.0#2]
So I tried running the run.sh scripts of fogcell and fogcontrolnode from run_scripts folder on my Raspberry Pi. On step 6, I get an error stating that the jffi/build.xml cannot find the jdk and the path of the JAVA_HOME is set to /usr/lib/jvm/java-8-openjdk-armhf/jre. Although i set the path to /usr/lib/jvm/java-8-openjdk-armhf/ in my environment variable. Any heads up on how I can resolve this issue.

Thanks

**Comment by softls** [comment]
On Raspberries, operating system is Hypriot. Base image of the docker file has to be hypriot/rpi-java
All custom libraries you use have to be added manually in the docker file and have to be physically present on the Raspberry. 
Also, please read the installation instructions specified in section 5.4 in this document, they are detailed: http://www.infosys.tuwien.ac.at/staff/sschulte/paper/Bachmann_Master.pdf
